### POST request to example server

POST localhost:4000/patients
Content-Type: application/json

{
  "name": "Bomba OOmba",
  "email": "testing_seervice1234@email.com",
  "address": "Earth",
  "dateOfBirth": "1995-03-09",
  "registeredDate": "2025-02-02"
}
###