### POST request to example server

POST http://localhost:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Bomba OOmbaaa",
  "email": "patientdonkey@email.com",
  "address": "Earth",
  "dateOfBirth": "1995-03-09",
  "registeredDate": "2025-02-02"
}
###